/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as ierc721Sol from "./IERC721.sol";
export type { ierc721Sol };
export type { IDroidBot } from "./IDroidBot";
export type { IERC20 } from "./IERC20";
export type { IERC721Receiver } from "./IERC721Receiver";
export type { IExchange } from "./IExchange";
export type { IStaking } from "./IStaking";
export type { ISwapRouter01 } from "./ISwapRouter01";
